version: "3.3"
services:
  oracle:
    image: "switchboardlabs/node:dev-v2-07-18-22"
    network_mode: host
    restart: always
    secrets:
      - PAYER_SECRETS
    environment:
      - LIVE=1
      - CLUSTER=devnet
      - HEARTBEAT_INTERVAL=30 # Seconds
      - ORACLE_KEY=Gdy6Tw2z2q92HR1DDjtX9SmPemzcwdGQwrYcTCg1rRdy
      - RPC_URL=https://solana-mainnet.g.alchemy.com/v2/WM_Gl7ktiws7icLQVxLP5iVHNQTv8RNk
    volumes:
      - ./configs.json:/configs.json
secrets:
  PAYER_SECRETS:
    file: ../../../jaregm.json

